// App action types
export const SET_APP_THEME = 'APP_STORE/SET_THEME'
export const SET_APP_BACKUP_TYPE = 'APP_STORE/SET_BACKUP_TYPE'
export const SET_APP_AUTO_BACKUP_DELAY = 'APP_STORE/SET_BACKUP_DELAY'
export const SET_APP_STORE = 'APP_STORE/SET'
export const SET_APP_SETTINGS = 'APP_STORE/SET_SETTINGS'
export const SET_APP_SELECTED_SETTING = 'APP_STORE/SET_SELECTED_SETTING'

// Task action types
export const SET_TASKS_STORE = 'TASKS_STORE/SET'
export const DELETE_ALL_TASKS = 'TASKS_STORE/DELETE_ALL'
export const DELETE_MULTIPLE_TASKS = 'TASKS_STORE/DELETE_MANY'
export const DELETE_ONE_TASK = 'TASKS_STORE/DELETE'
export const SAVE_TASK = 'TASKS_STORE/ADD'

// Board action types
export const ADD_BOARD = 'BOARD_STORE/ADD'
export const REMOVE_BOARD = 'BOARD_STORE/REMOVE'
export const REMOVE_ALL_BOARDS = 'BOARD_STORE/REMOVE_ALL'
export const SET_BOARD_STORE = 'BOARD_STORE/SET'
export const SET_CURRENT_BOARD = 'BOARD_STORE/SET_CURRENT'

// Panel action types
export const ADD_PANEL = 'PANEL_STORE/ADD'
export const REMOVE_PANEL = 'PANEL_STORE/REMOVE'
export const REMOVE_ALL_PANELS = 'PANEL_STORE/REMOVE_ALL'
export const SET_PANEL_STORE = 'PANEL_STORE/SET'
