// Main app store action types
const GET_MAIN_APP_STORE = 'MAIN_APP_STORE/GET'
const SAVE_TO_MAIN_APP_STORE = 'MAIN_APP_STORE/SET_KEY'
const DELETE_FROM_MAIN_APP_STORE = 'MAIN_APP_STORE/DELETE_KEY'
const CLEAR_MAIN_APP_STORE = 'MAIN_APP_STORE/CLEAR'
const SET_BACKUP_MAIN_APP_STORE = 'MAIN_APP_STORE/BACKUP'
const GET_FROM_MAIN_APP_STORE = 'MAIN_APP_STORE/GET_KEY'
const GET_BACKUP_MAIN_APP_STORE = 'MAIN_APP_STORE/GET_BACKUP'

// Notification action types
const SHOW_APP_NOTIFICATION = 'APP/SHOW_NOTIFICATION'

module.exports = {
	GET_MAIN_APP_STORE,
	GET_BACKUP_MAIN_APP_STORE,
	GET_FROM_MAIN_APP_STORE,
	SAVE_TO_MAIN_APP_STORE,
	SET_BACKUP_MAIN_APP_STORE,
	DELETE_FROM_MAIN_APP_STORE,
	CLEAR_MAIN_APP_STORE,
	SHOW_APP_NOTIFICATION,
}
