export const storageKeys = {
	APP: 'app',
	THEME: 'app.theme',
	BACKUP_TYPE: 'app.backup_type',
	AUTO_BACKUP_DELAY: 'app.auto_backup_delay',
	BOARDS: 'boards',
	CURRENT_BOARD_ID: 'boards.current_board_id',
	BOARDS_LIST: 'boards.boards_list',
	PANELS: 'panels',
	TASKS: 'tasks',
	PROJECTS: 'projects',
	PROJECTS_LIST: 'projects.projects_list',
	CURRENT_PROJECT_ID: 'project.current_project_id',
}

export const persistenceKeys = {
	ROOT: 'persist:root',
}

export const defaultReducerActions = {
	RESET_REDUCERS: 'DEFAULT_REDUCER/RESET',
}

export const appReducerActions = {
	SET_APP_THEME_TYPE: 'APP_STORE/SET_THEME_TYPE',
	SET_APP_BACKUP_TYPE: 'APP_STORE/SET_BACKUP_TYPE',
	SET_APP_AUTO_BACKUP_DELAY: 'APP_STORE/SET_BACKUP_DELAY',
	SET_APP_STORE: 'APP_STORE/SET',
}

export const projectsReducerActions = {
	SET_PROJECTS_STORE: 'PROJECTS_STORE/SET',
	SET_CURRENT_PROJECT_ID: 'PROJECTS_STORE/SET_CURRENT_ID',
	DELETE_ALL_PROJECTS: 'PROJECTS_STORE/DELETE_ALL',
	DELETE_MULTIPLE_PROJECTS: 'PROJECTS_STORE/DELETE_MANY',
	DELETE_PROJECT: 'PROJECTS_STORE/DELETE',
	ADD_PROJECT: 'PROJECTS_STORE/ADD',
}

export const tasksReducerActions = {
	SET_TASKS_STORE: 'TASKS_STORE/SET',
	DELETE_ALL_TASKS: 'TASKS_STORE/DELETE_ALL',
	DELETE_MULTIPLE_TASKS: 'TASKS_STORE/DELETE_MANY',
	DELETE_TASK: 'TASKS_STORE/DELETE',
	ADD_TASK: 'TASKS_STORE/ADD',
}

export const boardsReducerActions = {
	ADD_BOARD: 'BOARDS_STORE/ADD',
	DELETE_BOARD: 'BOARDS_STORE/DELETE',
	DELETE_MULTIPLE_BOARDS: 'BOARDS_STORE/DELETE_MANY',
	DELETE_ALL_BOARDS: 'BOARDS_STORE/DELETE_ALL',
	SET_BOARDS_STORE: 'BOARDS_STORE/SET',
	SET_CURRENT_BOARD_ID: 'BOARDS_STORE/SET_CURRENT_ID',
}

export const panelsReducerActions = {
	ADD_PANEL: 'PANELS_STORE/ADD',
	DELETE_PANEL: 'PANELS_STORE/DELETE',
	DELETE_MULTIPLE_PANELS: 'PANELS_STORE/DELETE_MANY',
	DELETE_ALL_PANELS: 'PANELS_STORE/DELETE_ALL',
	SET_PANELS_STORE: 'PANELS_STORE/SET',
}
